=== StBarCo/world_liturgy_app/assets/data/validate/songBooks.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="songbooks">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="revisions" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="version" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="date"/>
                    <xs:element type="xs:float" name="number"/>
                    <xs:element type="xs:string" name="notes"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="book">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title"/>
              <xs:element name="song" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType mixed="true">
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element type="xs:short" name="number"/>
                    <xs:element type="xs:string" name="title"/>
                    <xs:element type="xs:string" name="subtitle"/>
                    <xs:element name="verse">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="stanza" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="refrain">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="stanza" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="afterVerse"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== StBarCo/world_liturgy_app/assets/wlp_format/docs/songBooksSample.xml
<?xml version="1.0" encoding="UTF-8"?><!-- <?xml-stylesheet type="text/xsl" href="validate/worldLiturgy.xsl"?> --><!-- <prayer_books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='validate/prayerBooks.xsd'> -->
<songbooks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation='../validate/songBooks.xsd'>
  <revisions>
    <version>
      <date>10 Aug 2018</date>
      <number>1.0</number>
      <notes>Initial version of Tenzi Za Rohoni with Subtitles</notes>
    </version>

  </revisions>
  <book id='tenziZaRohoni'>
    <title>Tenzi Za Rohoni</title>
    <song>
      <number>1</number>
      <title>Mwokozi Umeokoa</title>
      <subtitle>Precious Saviour</subtitle>
      <verse>
        <stanza>Mwokozi umeokoa,</stanza>
        <stanza>Nimekuwa wako wewe.</stanza>
        <stanza>Damu imenisafisha;</stanza>
        <stanza>Sifa kwa mwana Kondoo.</stanza>
      </verse>
      <refrain>
        <stanza>Utukufu, Aleluya!</stanza>
        <stanza>Sifa kwa Mwana Kondoo!</stanza>
        <stanza>Damu imenisafisha,</stanza>
        <stanza>Utukufu kwa Yesu!</stanza>
      </refrain>
      <verse>
        <stanza>Nilijitahidi sana</stanza>
        <stanza>Ila sikupata raha;</stanza>
        <stanza>Bali kwa kumtegemea</stanza>
        <stanza>Nilipata Baraka.</stanza>
      </verse>
      <verse>
        <stanza>Daima namwegemea</stanza>
        <stanza>Damu ikifanya kazi,</stanza>
        <stanza>Nikioga kwa chemichemi</stanza>
        <stanza>Itokayo Mwokozi.</stanza>
      </verse>
      <verse>
        <stanza>Sasa nimewekwa wakfu;</stanza>
        <stanza>Nitaishi kwako wewe:</stanza>
        <stanza>Fahari nashuhudia</stanza>
        <stanza>Ya wokovu wa bure.</stanza>
      </verse>
      <verse>
        <stanza>Nasimama kwake Yesu,</stanza>
        <stanza>Ameponya roho yangu;</stanza>
        <stanza>Ameniondoa dhambi,</stanza>
        <stanza>Anifanye mzima.</stanza>
      </verse>
      <verse>
        <stanza>Nilikuwa kifungoni,</stanza>
        <stanza>Niliteswa na dhambi,</stanza>
        <stanza>Nilifungwa minyororo</stanza>
        <stanza>Yesu akanifungua.</stanza>
      </verse>
      <verse>
        <stanza>Sifa, ameninunua!</stanza>
        <stanza>Sifa, nguvu za wokovu!</stanza>
        <stanza>Sifa, Bwana huhifadhi!</stanza>
        <stanza>Sifa zake milele.</stanza>
      </verse>
    </song>
    <song>
      <number>2</number>
      <title>Twamsifu Mungu</title>
      <subtitle>We Praise Thee, O God</subtitle>
      <verse>
        <stanza>Twamsifu Mungu kwa Mwana wa Pendo,</stanza>
        <stanza>Aliyetufia na kupaa juu.</stanza>
      </verse>
      <refrain>
        <stanza>Aleluya! Usifiwe; Aleluya! Amin.</stanza>
        <stanza>Aleluya! Usifiwe, utubariki.</stanza>
      </refrain>
      <verse>
        <stanza>Twamsifu Mungu kwa Roho Mtukufu,</stanza>
        <stanza>Ametufunulia Mwokozi wetu.</stanza>
      </verse>
      <verse>
        <stanza>Twamsifu Mwana, aliyetufia,</stanza>
        <stanza>Aliyetwaa dhambi akazifuta.</stanza>
      </verse>
      <verse>
        <stanza>Twamsifu Mungu wa neema yote,</stanza>
        <stanza>Ametukomboa akatuongoza.</stanza>
      </verse>
      <verse>
        <stanza>Tuamshe tena, tujazena pendo,</stanza>
        <stanza>Na moyoni uwashe moto wa Roho.</stanza>
      </verse>
    </song>
    <song>
      <number>3</number>
      <title>Hata Ndimi Elfu</title>
      <subtitle>O for a Thousand Tongues to Sing</subtitle>
      <verse>
        <stanza>Hata ndimi elfu elfu,</stanza>
        <stanza>Hazitoshi kweli</stanza>
        <stanza>Bwana Yesu kumsifu,</stanza>
        <stanza>Kwa zake fadhili.</stanza>
      </verse>
      <verse>
        <stanza>Yesu, jina liwezalo</stanza>
        <stanza>Kufukuza hofu;</stanza>
        <stanza>Lanifurahisha hilo,</stanza>
        <stanza>Lanipa wokovu.</stanza>
      </verse>
      <verse>
        <stanza>Jina hilo ni uzima;</stanza>
        <stanza>Ni afya amani;</stanza>
        <stanza>Laleta habari njema;</stanza>
        <stanza>Twalipiwa deni.</stanza>
      </verse>
      <verse>
        <stanza>Yesu huvunja mapingu</stanza>
        <stanza>Ya dhambi moyoni;</stanza>
        <stanza>Msamaha, tena nguvu,</stanza>
        <stanza>Twapata rohoni.</stanza>
      </verse>
      <verse>
        <stanza>Kwa sauti yake vile</stanza>
        <stanza>Wafu hufufuka</stanza>
        <stanza>Wakafurahi milele,</stanza>
        <stanza>Pasipo mashaka.</stanza>
      </verse>
      <verse>
        <stanza>Ewe Yesu wangu Bwana,</stanza>
        <stanza>Uwezo nipewe,</stanza>
        <stanza>Kuhubiri kote sana,</stanza>
        <stanza>Wote wakujue.</stanza>
      </verse>
    </song>
    <song>
      <number>4</number>
      <title>Jina la Yesu, salamu!</title>
      <subtitle>All Hail the Power of Jesus' Name</subtitle>
      <verse>
        <stanza>Jina la Yesu, Salamu!</stanza>
        <stanza>Lisujudieni,</stanza>
        <stanza>Ninyi Mbinguni, hukumu</stanza>
        <stanza>Na enzi mpeni.</stanza>
      </verse>
      <verse>
        <stanza>Enzi na apewe kwetu,</stanza>
        <stanza>Watetea dini;</stanza>
        <stanza>Mkuzeni Bwana wenu,</stanza>
        <stanza>Na enzi mpeni.</stanza>
      </verse>
      <verse>
        <stanza>Enyi mbegu ya rehema,</stanza>
        <stanza>Nanyi msifuni;</stanza>
        <stanza>Mmeponywa kwa neema,</stanza>
        <stanza>Na enzi mpeni.</stanza>
      </verse>
      <verse>
        <stanza>Wenye dhambi kumbukeni</stanza>
        <stanza>Ya msalabani,</stanza>
        <stanza>Kwa furaha msifuni,</stanza>
        <stanza>Na enzi mpeni.</stanza>
      </verse>
      <verse>
        <stanza>Kila mtu duniani</stanza>
        <stanza>Msujudieni,</stanza>
        <stanza>Kote-kote msifuni,</stanza>
        <stanza>Na enzi mpeni.</stanza>
      </verse>
      <verse>
        <stanza>Sisi na wao pamoja</stanza>
        <stanza>Tu mumo sifani,</stanza>
        <stanza>Milele sifa ni moja,</stanza>
        <stanza>Ni “Enzi mpeni.”</stanza>
      </verse>
    </song>
    <song>
      <number>5</number>
      <title>Jina Lake Yesu Tamu</title>
      <subtitle>How Sweet the Name of Jesus Sounds</subtitle>
      <verse>
        <stanza>Jina lake Yesu tamu;</stanza>
        <stanza>Tukilisikia</stanza>
        <stanza>Hutupoza, tena hamu</stanza>
        <stanza>Hutuondolea.</stanza>
      </verse>
      <verse>
        <stanza>Roho iliyoumia</stanza>
        <stanza>Kwalo hutibika,</stanza>
        <stanza>Chakula, njaani pia;</stanza>
        <stanza>Raha, tukichoka.</stanza>
      </verse>
      <verse>
        <stanza>Jina hili ni msingi,</stanza>
        <stanza>Ngao, ngome, mwamba,</stanza>
        <stanza>Kwa hili napata wingi,</stanza>
        <stanza>Kwangu ni akiba.</stanza>
      </verse>
      <verse>
        <stanza>Yesu, Mchunga, Rafiki</stanza>
        <stanza>Mwalimu, Kuhani,</stanza>
        <stanza>Mwanzo, Mwisho, Njia, Haki,</stanza>
        <stanza>Uzima kifoni.</stanza>
      </verse>
      <verse>
        <stanza>Moyo wangu hauwezi,</stanza>
        <stanza>Kukusifu kweli,</stanza>
        <stanza>Ila sifa zangu hizi,</stanza>
        <stanza>Bwana zikubali.</stanza>
      </verse>
      <verse>
        <stanza>Na utakaponiita,</stanza>
        <stanza>Kuja kwako Bwana,</stanza>
        <stanza>Huko kwako sitaacha</stanza>
        <stanza>Kukusifu sana.</stanza>
      </verse>
    </song>
    <song>
      <number>6</number>
      <title>Baba, Mwana, Roho</title>
      <subtitle>Holy Holy Holy, Lord God Almighty</subtitle>
      <verse>
        <stanza>Baba, Mwana, Roho, Mungu mwenye enzi,</stanza>
        <stanza>Kila tukiamka tunakuabudu</stanza>
        <stanza>Baba, Mwana, Roho, Mungu wa mapenzi,</stanza>
        <stanza>Ewe Utatu, tunakusifu.</stanza>
      </verse>
      <verse>
        <stanza>Baba, Mwana, Roho, wakuaminio</stanza>
        <stanza>Wanakutolea shukrani zao</stanza>
        <stanza>Wanakusujudia malaika nao:</stanza>
        <stanza>Wewe u mwanzo, nawe u mwisho.</stanza>
      </verse>
      <verse>
        <stanza>Baba, Mwana, Roho, sisi tu gizani,</stanza>
        <stanza>Utukufu wako hatuoni kosa;</stanza>
        <stanza>U Mtakatifu, nawe u mapenzi,</stanza>
        <stanza>U peke yako, mwenzio huna.</stanza>
      </verse>
      <verse>
        <stanza>Baba, Mwana, Roho, Mungu mwenye enzi,</stanza>
        <stanza>Ulivyoviumba vyote vyakusifu:</stanza>
        <stanza>Baba, Mwana, Roho, Mungu wa mapenzi</stanza>
        <stanza>Ewe Utatu, tunakusifu.</stanza>
      </verse>
    </song>
    <song>
      <number>7</number>
      <title>Ni tabibu wa Karibu</title>
      <subtitle>The Great Physician Now Is Near</subtitle>
      <verse>
        <stanza>Ni tabibu wa karibu;</stanza>
        <stanza>Tabibu wa ajabu;</stanza>
        <stanza>Na rehema za daima;</stanza>
        <stanza>Ni dawa yake njema.</stanza>
      </verse>
      <refrain>
        <stanza>Imbeni, malaika,</stanza>
        <stanza>Sifa za Yesu Bwana;</stanza>
        <stanza>Pweke limetukuka</stanza>
        <stanza>Jina lake Yesu.</stanza>
      </refrain>
      <verse>
        <stanza>Hatufai kuwa hai,</stanza>
        <stanza>Wala hatutumai,</stanza>
        <stanza>Ila kweli yeye ndiye</stanza>
        <stanza>Atupumzishaye.</stanza>
      </verse>
      <verse>
        <stanza>Dhambi pia na hatia</stanza>
        <stanza>Ametuchukulia;</stanza>
        <stanza>Twendeni na amani</stanza>
        <stanza>Hata kwake Mbinguni.</stanza>
      </verse>
      <verse>
        <stanza>Huliona tamu jina</stanza>
        <stanza>La Yesu Kristo Bwana,</stanza>
        <stanza>Yuna sifa mwenye kufa</stanza>
        <stanza>Asishindwe na kufa.</stanza>
      </verse>
      <verse>
        <stanza>Kila mume asimame,</stanza>
        <stanza>Sifa zake zivume;</stanza>
        <stanza>Wanawake na washike</stanza>
        <stanza>Kusifu jina lake.</stanza>
      </verse>
      <verse>
